export default [
  {
    logo: '../bookmarks/p1.png',
    name: 'Cook Roberin',
    handler: '@cook_roberin',
    time: 'Jul 31',
    firstParagraph: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    blueStress:'@Inspiration4x',
    picture: '../bookmarks/p2.png',
    secondStress:'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    secondParagrapg:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    lastLogo:'netflix.com',
    comment:'4.2K',
    retweet:'3.5K',
    love:'37.5K',
  },
  {
    logo: '../bookmarks/p2.png',
    name: 'Musks Hoddinson',
    handler: '@musks_hoddison',
    time: '23h',
    firstParagraph: 'These days it is the Kremlin that is praising Georgia, a country it invaded in 2008, for toeing its line and refusing to join Western sanctions against Russia fighting dementia and muscle atrophy. His mother, who visits hur correspondent in a letter.',
    blueStress:'trib.al/nx2Gfaq',
    picture: '../bookmarks/p3.png',
    secondStress:'',
    secondParagrapg:'',
    lastLogo:'rt.com',
    comment:'999K',
    retweet:'9.9K',
    love:'99.9K',
  },
  {
    logo: '../bookmarks/p3.png',
    name: 'New York Post',
    handler: '@nypost',
    time: 'Yesterday',
    firstParagraph: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    blueStress:'@Inspiration4x',
    picture: '../bookmarks/p4.png',
    secondStress:'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    secondParagrapg:'',
    lastLogo:'rt.com',
    comment:'99K',
    retweet:'8.8K',
    love:'39.9K',
  },

];